labelPRBasedOnFilePath:
  "Documentation 📚":
    - README.md
    - CONTRIBUTING.md
  "Dependencies 📦":
    - Dockerfile*
    - composer.*
    - package.json
    - package-lock.json
    - yarn.lock
  "Docker 🐳":
    - Dockerfile*
    - .docker/**/*
  "Image 🖼":
    - "**/*.gif"
    - "**/*.jpg"
    - "**/*.jpeg"
    - "**/*.png"
    - "**/*.webp"
  "CSS 👩‍🎨":
    - "**/*.css"
  "HTML 👷‍♀️":
    - "**/*.htm"
    - "**/*.html"
  "NEON 🦹‍♂️":
    - "**/*.neon"
  "MarkDown 📝":
    - "**/*.md"
  "YAML 🍄":
    - "**/*.yml"
    - "**/*.yaml"
  "JSON 👨‍💼":
    - "**/*.json"
  "Go 🐹":
    - "**/*.go"
  "JavaScript 🦏":
    - "**/*.js"
    - package.json
    - package-lock.json
    - yarn.lock
  "PHP 🐘":
    - "**/*.php"
    - composer.*
  "Configuration ⚙":
    - .github/*
  "CI 🚧":
    - .github/workflows/*
    - .scrutinizer.yml
  "Templates 🌲":
    - "**/*.twig"
    - "**/*.tpl"
  "Helm ☸":
    - .helm/**/*
  "Tests 🧪":
    - tests/**/*
  "Source 🔮":
    - src/**/*

labelerFlags:
  labelOnPRUpdates: true
