; Avoid zend_mm_heap corruption with #[WithSpan] (mammatus uses hook() instead).
; See: https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/321
; Already solved: https://github.com/open-telemetry/opentelemetry-php-instrumentation/pull/313
opentelemetry.attr_hooks_enabled=Off
